spring.cloud.stream.bindings.output.destination: twitchMessages
spring.cloud.stream.default.contentType: application/json

server:
  port: 9000

twitch:
  botNick: indysfug
  channel: "hireztv"
  oauthToken: CHANGE_ME

