spring.cloud.stream.bindings.input.destination: twitchMessages
spring.cloud.stream.bindings.input.durableSubscription: false
spring.cloud.stream.bindings.input.group: emotewatcher
spring.cloud.stream.bindings.output.destination: twitchChatEmotes
spring.cloud.stream.default.contentType: application/json
